### ISSUE TITLE
Any ideas? Not working.

### ISSUE THREAD

**Issue by cjemorton** [skoef/mondieu#4]
Any idea on how to update a tier 2 device?

> root@rpi:~ # uname -a
> FreeBSD rpi 11.2-RELEASE FreeBSD 11.2-RELEASE #0 r335510: Fri Jun 22 02:35:12 UTC 2018     root@releng2.nyi.freebsd.org:/usr/obj/arm.armv6/usr/src/sys/RPI-B  arm
> 
> 
> root@rpi:~ # ./mondieu 12.0-RELEASE
> Fri Aug  3 23:03:54 MST 2018 ==> Preparing work space ... done
> Fri Aug  3 23:03:54 MST 2018 ==> Fetching release 12.0-RELEASE ... kernel fetch: http://ftp.freebsd.org/pub/FreeBSD/releases/arm/12.0-RELEASE//kernel.txz: Not Found
> 
> Could not fetch http://ftp.freebsd.org/pub/FreeBSD/releases/arm/12.0-RELEASE//kernel.txz
> Fri Aug  3 23:03:55 MST 2018 ==> Cleaning up ... done
>

**Comment by skoef** [comment]
So, the actual problem here is there are now tarballs for 12.0-RELEASE (or any release for that matter) in the [arm](http://ftp.freebsd.org/pub/FreeBSD/releases/arm/) architecture folder, where this is the case for [amd64](http://ftp.freebsd.org/pub/FreeBSD/releases/amd64/12.0-RELEASE/), [arm64](http://ftp.freebsd.org/pub/FreeBSD/releases/arm64/12.0-RELEASE/), [i386](http://ftp.freebsd.org/pub/FreeBSD/releases/i386/) etc. I'm not sure what FreeBSD's policy is for arm, but if you manage to find the tarballs, you can use the `-U` parameter to point to the URL where to download these.

**Comment by cjemorton** [comment]
Thanks, that’s basically the conclusion I came to.
As an afterthought here. I wonder if anyone hosts arm tarballs anywhere. If anyone knows or does send me a link.
I could always cross compile and host it locally on my poudiere pkg build server, but I’d rather not go to all that trouble if someone already has.
